<a href="https://colab.research.google.com/github/carthmannH/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print ("Hello I'm excited to learn pytorch")

Hello I'm excited to learn pytorch


In [3]:
!nvidia-smi

Mon Apr 22 15:39:50 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
import torch

In [7]:
torch.__version__

'2.2.1+cu121'

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [10]:
#scalar
scalar = torch.tensor(7)

In [11]:
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [14]:
scalar.item()

7

In [16]:
vector = torch.tensor([7, 7])

In [17]:
vector

tensor([7, 7])

In [18]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([2])

In [21]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [22]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [25]:
MATRIX[0]

tensor([7, 8])

In [23]:
MATRIX.ndim

2

In [26]:
MATRIX[1]

tensor([ 9, 10])

In [27]:
MATRIX.shape

torch.Size([2, 2])

In [28]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [29]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 3, 3])

In [33]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [34]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7424, 0.5187, 0.3788, 0.7652],
         [0.4793, 0.5031, 0.2699, 0.2934],
         [0.9297, 0.8814, 0.9111, 0.4716]]),
 torch.float32)

In [35]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [36]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [38]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.arange(0, 10) # Note: this may return an error in the future


In [39]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])